/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication23;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author iiita
 */
public class DischargePatient extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form DischargePatient
     */
    public DischargePatient() {
        initComponents();
    }
    
    public String CurrentDate() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        return (day + "/" + (month + 1) + "/" + year);
        /*System.out.println("Current date : "
                + day + "/" + (month + 1) + "/" + year);*/
    }
    
    public int getIntDate(String str){
        int date=0, a=0,b=0,c=0;
        
        a=Integer.parseInt(str.substring(0,2));
        b=Integer.parseInt(str.substring(3,5));
        c=Integer.parseInt(str.substring(6,10));
        
        date = c*10000 + b *100 + a;
        
        return date;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regNo = new javax.swing.JLabel();
        txtRegNo = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        btnDischarge = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regNo.setText("Reg. No.");

        txtRegNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPayment.setText("Pay Bills");
        btnPayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnDischarge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDischarge.setText("Discharge");
        btnDischarge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDischarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DISCHARGE PATIENT / PAY BILLS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDischarge)
                            .addComponent(btnPayment)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(regNo)
                            .addGap(74, 74, 74)
                            .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel1))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNo)
                    .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnPayment)
                .addGap(18, 18, 18)
                .addComponent(btnDischarge)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDischargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargeActionPerformed
        // TODO add your handling code here:
       
        
        
        Connect_db connect = new Connect_db();
        conn = connect.ConnecrDb(); 
        
        String sql = "delete from PatientDetails where RegNo = ?";
        
        try{
            int count=0,bednum=0;
            String wardType="";
            String query = "select * from PatientDetails where RegNo = ?";
            pst = conn.prepareStatement(query);
            pst.setString(1,txtRegNo.getText());
            rs = pst.executeQuery();
            
            while(rs.next()){
                count=count+1;
                wardType=rs.getString("WardType");
                bednum=rs.getInt("BedNo");
            }
            if(count==0){
                JOptionPane.showMessageDialog(null, "Patient not found.");
                conn.close();
            }
            else{
                pst = conn.prepareStatement(sql);
            
                pst.setString(1,txtRegNo.getText());
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Patient Discharged.");
                
                if(wardType.equals("ICU")){
                    query = "update BedDetail set ICU = ? where BedNo = ? ";
                    pst = conn.prepareStatement(query);
                    pst.setString(1,"Available");
                    pst.setInt(2,bednum);
                    pst.executeUpdate();
                }
                else{
                    query = "update BedDetail set General = ? where BedNo = ? ";
                    pst = conn.prepareStatement(query);
                    pst.setString(1,"Available");
                    pst.setInt(2,bednum);
                    pst.executeUpdate();
                }
                
                
                
                
                
                Interfacer s = new Interfacer();
                s.setVisible(true);
                
                
                
                conn.close();
            }
            
        }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);

        }   
    }//GEN-LAST:event_btnDischargeActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
         String last_date = "",current_Ward="", currentDate=CurrentDate();
        int days=0, transfers=0, General_days=0, ICU_days=0;
        
        Connect_db connect = new Connect_db();
        conn = connect.ConnecrDb();
        
        
        try{
            String sql = "select * from PatientDetails where RegNo = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,txtRegNo.getText());
            
            rs = pst.executeQuery();
            
            
            while(rs.next()){
                last_date = rs.getString("lastChangeDate");
                current_Ward = rs.getString("WardType");
                transfers = rs.getInt("NoofWardTrns");
                General_days = rs.getInt("daysGeneral");
                ICU_days = rs.getInt("daysICU");   
            }
            
            if(last_date.equals(currentDate)){
                days=1;
            }
            else{
                days = getIntDate(currentDate)-getIntDate(last_date);
            }
            
            if(current_Ward.equals("General")){
                sql = "update PatientDetails set WardType = ?, NoofWardTrns = ?, lastChangeDate = ?, daysGeneral = ? where RegNo = ?";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1,"General");
                pst.setInt(2,transfers);
                pst.setString(3,currentDate);
                pst.setInt(4,days+General_days);
                pst.setString(5,txtRegNo.getText());
                
                pst.executeUpdate();
            }
            else{
                sql = "update PatientDetails set WardType = ?, NoofWardTrns = ?, lastChangeDate = ?, daysICU = ? where RegNo = ?";
                
                pst = conn.prepareStatement(sql);
                
                pst.setString(1,"ICU");
                pst.setInt(2,transfers);
                pst.setString(3,currentDate);
                pst.setInt(4,days+ICU_days);
                pst.setString(5,txtRegNo.getText());
                
                pst.executeUpdate();
            }
            
            conn.close();
            
            
        }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        Payment pay = new Payment(txtRegNo.getText());
        pay.setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DischargePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DischargePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DischargePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DischargePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DischargePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDischarge;
    private javax.swing.JButton btnPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel regNo;
    private javax.swing.JTextField txtRegNo;
    // End of variables declaration//GEN-END:variables
}
